markdown: kramdown
pygments: true
permalink: /:year/:month/:day/:title

url: http://quanqi.org
baseurl:

redcarpet:
    extensions: [strikethrough, tables]

duoshuo :
    short_name : quanqi
    enable : true

google_plus :
    id : 101733574037044507534
    enable_search_refer : true
